---
- hosts: master
  become: yes
  tasks:
    # Initialize Cluster. The log is also used to prevent an second initialization
    - name: Initialize Cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem >> cluster_init.log
      args:
        chdir: $HOME
        creates: cluster_init.log

    - name: Create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to the user's kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: install Pod network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    # =================================================================================
    # To be able to run kubectl from jenkins controller
    # =================================================================================
    - name: Fetch kube config
      slurp:
        src: /etc/kubernetes/admin.conf
      register: kube_config

    - name: Decode config and store as fact
      set_fact:
        kube_config: "{{ kube_config['content'] | b64decode }}"

    - name: Create local kubernetes directory
      file:
        path: /opt/shared/kubernetes
        state: directory
      delegate_to: localhost

    - name: Copy kube config to local config
      local_action: copy content="{{ kube_config }}" dest="/opt/shared/kubernetes/admin.conf"

    # - name: Set kubecongif environment variable
    #   lineinfile:
    #     dest: "/etc/environment"
    #     state: present
    #     line: "KUBECONFIG=/opt/shared/kubernetes/admin.conf"
    #   delegate_to: localhost
    # =================================================================================
