---
- hosts: master
  become: yes
  tasks:
    - name: initializing  kubeadm service
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
      ignore_errors: yes

    - name: create .kube directory
      file:
        path: /home/ec2-user/.kube
        state: directory
        mode: "0755"

    - name: Copy file with owner and permissions
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ec2-user/.kube/config
        remote_src: yes
        group: ec2-user

    - name: Copy file with owner and permissions
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /var/lib/jenkins/.kube/config
        remote_src: yes
        group: jenkins
        user: jenkins

    - name: Copy config to ansible controller
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home/ec2-user/.kube/config
        flat: yes

    - name: install Pod network
      become: yes
      become_user: ec2-user
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Remove master node taint (to allow scheduling pods on master)
      shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

    - name: Generate the token
      shell: "kubeadm token create --print-join-command"
      register: token

    - name: Print the token
      debug:
        var: token.stdout_lines
