---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Print the token
      debug:
        msg: "{{ join_command_raw.stdout }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars[item]['join_command'] }} --ignore-preflight-errors all >> join_cluster.txt"
      with_items: "{{ groups['master'] }}"
      args:
        chdir: $HOME
        creates: join_cluster.txt
