apiVersion: apps/v1
kind: Deployment
metadata:
  name: koko-devops-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: koko-devops-app
  template:
    metadata:
      labels:
        app: koko-devops-app

    spec:
      containers:
        - name: koko-devops-app
          image: 280052623973.dkr.ecr.eu-west-3.amazonaws.com/koko-devops-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
