apiVersion: v1
kind: Service
metadata:
  name: koko-devops-service
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      name: http
      targetPort: 5000
      nodePort: 30500
  selector:
    app: koko-devops-app
